# Generated by Django 5.1 on 2024-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_movies_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Comedy', 'Comedy')], max_length=200),
        ),
    ]
